# Generated by Django 5.2.8 on 2025-11-27 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoptions_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='pets.pet'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['pet_type', 'status'], name='pets_pet_pet_typ_a44fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['location'], name='pets_pet_locatio_44d479_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionrequest',
            index=models.Index(fields=['status'], name='pets_adopti_status_a4bbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionrequest',
            index=models.Index(fields=['user', 'status'], name='pets_adopti_user_id_797209_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adoptionrequest',
            unique_together={('user', 'pet')},
        ),
    ]
