# Generated by Django 5.2.8 on 2025-11-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional image URLs', null=True),
        ),
    ]
