# Generated by Django 5.2.8 on 2025-11-27 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accessories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='accessories.category'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'accessory')},
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['category', 'is_active'], name='accessories_categor_04e6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['is_featured', 'is_active'], name='accessories_is_feat_3828e1_idx'),
        ),
    ]
