# Generated by Django 5.2.8 on 2025-11-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
